apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: ew0w8ed3w-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-de67c15444.tl39.p3.openshiftapps.com/rhtap/rhtap-qe:c07c93176310700dbacfbabf4bc6ee562d85da58@sha256:f130aae91a5758f49f2f2aad3cedd15415cd458b0430d746d63e05c078b56e64
        name: container-image  
